research_task:
  description: >
    Conduct a thorough symptoms analysis of {input}. Be sure to look for formal sources, and compile a list of 
    the most relevant diseases, conditions, medications, and treatment protocols associated with {input}

    Follow these rules:
    - Only include medical proven diagnoses based on the {input}
    - Suggest potential diagnoses based on the input provided.
    - Recommend an observation period.
    - Include a minimum of ten treatment options and recommendations.
    - Format for Sources: [Author, Year] (Name of journal) and <DOI or article url>

  expected_output: >
    A markdown document with the most relevant diagnostics and available treatment options for the provided {input}.
    Each diagnosis must contain
    - The symptom
    - The diagnosis
    - Summary of available treatment options
    - Recommend immediate actions if necessary
    Here is an example output format to include in your document:

    <EXAMPLE>
      Symptom {input}:
      - Diagnosis: [Condition]
      - Treatment Options: 
          - Treatment1
          -  Treatment2
      - References: 
          - Reference1
          - Reference2

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.

    
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
